version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 200901485389.dkr.ecr.us-east-1.amazonaws.com/node-app
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t node-app:latest .
      - docker tag node-app:latest 200901485389.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 200901485389.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
